config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :exercices, only: [:index, :show, :new, :create] do
    resources :answers, only: [:create, :update, :show]
    get 'publish', to: 'answers#publish'
  end

  resources :answers, only: [] do
    resources :comments, only: [:create]
  end
  get '/answers/:id/like', to: 'answers#like', as: 'answers_like'

  resources :answers, only: [:index]

  # get 'answer/user_id/edit', to: 'users#edit', as: 'edit_user'

  resources :users, only: [:edit, :update, :show]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Copyright © 2017 MhistO
  </div>

  <div class="logo" id="logo-footer">
    MHISTO
  </div>
</div>

app/views/shared/_navbar.html.erb
  <header class="navbar-wagon-without-line navbar-wagon">
    <!-- Logo -->
    <%= link_to root_path, class: "logo" do %>
    <div>
      MHISTO
    </div>
    <% end %>

    <!-- Right Navigation -->
    <div class="navbar-wagon-right hidden-xs hidden-sm">

      <% if user_signed_in? %>

        <!-- Links when logged in -->
        <%= link_to "Proposer un exo", new_exercice_path, class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag avatar_url = current_user.facebook_picture_url || current_user.avatar || 'https://api.adorable.io/avatars/285/abott@adorable.png', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to answers_path  do %>
                  <i class="fa fa-user"></i>&nbsp;&nbsp;<%= t(".profile", default: "Dashboard") %>
                <% end %>
              </li>
              <li>
                <%= link_to exercices_path do %>
                  <i class="fa fa-home"></i>&nbsp;&nbsp;<%= t(".profile", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>&nbsp;&nbsp;<%= t(".sign_out", default: "Déconnexion") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_up", default: "Sign Up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
    </div>

    <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Some mobile link</a></li>
          <li><a href="#">Other one</a></li>
          <li><a href="#">Other one</a></li>
        </ul>
      </div>
    </div>
  </header>