config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

    root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :exercices, only: [:index, :show, :new, :create] do
    resources :answers, only: [:create, :update, :show]
    get 'publish', to: 'answers#publish'
  end

  resources :answers, only: [] do
    resources :comments, only: [:create]
  end
  get '/answers/:id/like', to: 'answers#like', as: 'answers_like'

  resources :answers, only: [:index]

  # get 'answer/user_id/edit', to: 'users#edit', as: 'edit_user'

  resources :users, only: [:edit, :update, :show]

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :exercice

  has_many :comments
  has_many :likes
  validates :content, presence: true

  acts_as_votable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  after_action :verify_authorized, :except => [:create, :index, :like, :update, :show]

  def index
    @answers = Answer.where(user_id: current_user.id)
    # @answers = policy_scope(Answer).where(user_id: current_user.id).order(created_at: :desc)
    # @exercices = Exercice.where(user_id: current_user.id)
    @exercices = policy_scope(Exercice).where(user_id: current_user.id).order(created_at: :desc)
  end

  def show
    set_exercice
    @answers = @exercice.answers
    @answer = Answer.find(params[:id])
  end

  def new

  end

  def create
    set_exercice
    @answer = Answer.new(answer_params)
    @answer.exercice = @exercice
    @answer.user = current_user
    @answer.status = "published" unless params[:publish].nil?
    if @answer.save
      respond_to do |format|
        format.html { redirect_to exercice_path(@exercice) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render "exercices/show" }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    end
  end

  def update
    set_exercice
    @answer = Answer.find(params[:id])
    @answer.update(content: params[:answer][:content])
    @answer.update(status: "published") unless params[:publish].nil?
    @comment = Comment.new
    respond_to do |format|
      format.html { redirect_to exercice_path(@exercice) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  def publish
    set_exercice
    @answer = @exercice.answers.find_by_user_id(current_user.id)
    @answer.update(status: "published")
  end

  def like
    @answer = Answer.find(params[:id])
    @answer.liked_by current_user
    # @answer.unlike_by current_user
    respond_to do |format|
      format.html { redirect_to exercice_path(@answer.exercice) }
      format.js  # <-- will render `app/views/reviews/create.js.erb`
    end
  end

  private
  def set_exercice
    @exercice = Exercice.find(params[:exercice_id])
  end

  def answer_params
    params.require(:answer).permit(:content, :user_id, :exercice_id)
  end
end

app/views/answers/_form.html.erb
<div class="form-container">
  <div class="begin-story">
  <h6>Début</h6>
  <%= @exercice.beginning_story %>
  </div>

  <div class="form-answer">
    <div class="save-counter">

            <div class="word-counter">
              <p># de mots:&nbsp;</p><p id="words-count"></p>
            </div>
            <div id='save-auto' class='answer_auto_save'>
            </div>

          </div>
    <%= simple_form_for [exercice, answer], html: {class: 'my-answer-form'}, remote: true do |a| %>
      <%= a.input :content, required: false, label: false, placeholder: "À vous d'écrire le milieu", input_html: { spellcheck: false, autocorrect: "off" } %>
      <%= a.submit 'Sauvegarder le texte', class: "orange_color", id: "save-text-auto", hidden: true %>
  <div class="ending-story">
    <h6>Fin</h6>
    <%= @exercice.end_story %>
  </div>
  <div class="end-story">
  </div>
      <%= a.submit 'Publier', name: "publish", class: "orange_color" %>
  </div>
    <% end %>
</div>

app/views/answers/_like.html.erb
<!-- <div class="likes-comments" id='answer_id_<%= answer.id %>'> -->
    <!-- TODO grey when likes == 0 and change display on hover if user votes for it or not -->
<% if answer.votes_for.voters.include? current_user %>

        <div class="liked">
            <i class="fa fa-heart" aria-hidden="true"></i>
            <%= answer.votes_for.size %>
        </div>
      <% else %>
        <div class="likes">
          <%= link_to answers_like_path(answer), remote: true do %>
            <i class="fa fa-heart" aria-hidden="true"></i>
            <%= answer.votes_for.size %>
          <% end %>
        </div>
      <% end %>

app/views/answers/_show.html.erb
<div class="answer">
  <div class="answer-infos">
    <div class="avatar-username">
      <h6><%= image_tag answer.user.avatar || answer.user.facebook_picture_url || 'https://api.adorable.io/avatars/285/abott@adorable.png', class: "avatar-answer" %>&nbsp;</h6>
      <h6 class="avatar-hidden"><%= link_to answer.user.username, user_path(answer.user) %></h6>
    </div>


    <% maxvote = 1 %>
    <% @exercice.answers.each do |ans| %>
      <% if ans.votes_for.size >= maxvote %>
        <% maxvote = ans.votes_for.size %>
      <% end %>
    <% end %>

    <% if answer.votes_for.size == maxvote %>

      <div class="congrats-winner">Félicitations à <%= answer.user.username %> qui est en tête des votes!</div>
    <%end %>

    <div class="likes-comments" id='answer_id_<%= answer.id %>'>
      <%= render 'answers/like', answer: answer %>
    </div>
  </div>
  <div class="show-collapse">
    <p><%= answer.content.first(310) %>...</p>
  </div>
  <div class="hide-collapse" style="display: none;">
    <div class="debut-answer">
      <h6>Début</h6>
      <i class="fa fa-minus" aria-hidden="true"></i>

    </div>
    <p><%= @exercice.beginning_story %></p>
    <div id="answer_content_collapse"><%= answer.content %></div>
    <h6>Fin</h6>
    <p><%= @exercice.end_story %></p>
  </div>

<!--   <div class="answer-content">
    <%= simple_format answer.content %>
  </div> -->


  <div class="comments-container">
    <% if answer.comments.count == 0 %>
      <div class="show-comments">
        Commenter
      </div>
    <% else %>
      <div class="show-comments">
        <%= pluralize answer.comments.count, "Commentaire" %>
      </div>
    <% end %>
    <div class="hide-comments">
      Masquer
    </div>
    <div class="answer-comments">
      <% if answer.comments.count != 0 %>
        <ul>
          <% answer.comments.each do |comment| %>
            <div class="comment-content">
              <li><%= comment.content %></li>
              <div class="commentor">
                <li>par&nbsp;</li>
                <li class="user-commentor"><%= comment.user.username %></li>
              </div>
            </div>
          <% end %>
        </ul>
      <% else %>

    <% end %>

        <div class="new-comment">
        <%= simple_form_for [answer, @comment] do |c| %>
          <%= c.input :content, label: '', placeholder: 'Écrivez un commentaire'  %>
          <%= c.submit 'Commenter', class: "orange_color" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/answers/create.js.erb
<% if @answer.errors.any? %>
<% elsif @answer.status == 'published' %>

<% else %>
  // put a edit form
  const form = "<%= j render 'answers/form', exercice: @exercice, answer: @answer %>";
  document.getElementById('answer_form_wrapper').innerHTML = form;

  document.getElementById('answer_content').addEventListener('keyup', function(event) {

    var count = 0;
    event.target.value.split(" ").forEach(function(val) {
      if (val !== "") {
        count++;
      }
    });

    document.getElementById('words-count').innerText = count;
    document.getElementById('save-text-auto').click();

    document.getElementById('answer_content').addEventListener('click', function(event) {
      event.target.classList.add("answer-content-grow");
    });

    document.addEventListener('click', function(event) {
      console.log(event.target.id);
      if (event.target.className.indexOf("answer-content-grow") === -1) {
        if (event.target.id != "save-text-auto") {
          document.getElementById('answer_content').classList.remove("answer-content-grow");
         }
      }
    });

  });
  document.getElementById('answer_content').classList.add("answer-content-grow");
  // document.getElementById('answer_content').focus();
  // // document.querySelector('.answer-content-grow').focus();

  var monInput = document.getElementById('answer_content');
  var strLength = monInput.value.length * 2;

  monInput.focus();
  monInput.setSelectionRange(strLength, strLength);

  document.getElementById('save-auto').innerText = "Save"

<% end %>

app/views/answers/index.html.erb
<div class="container">
  <div class="tab">
    <button class="tablinks active" onclick="openDashTab(event, 'MyAnswers')">Mes réponses</button>
    <button class="tablinks" onclick="openDashTab(event, 'MyExercices')">Mes exercices</button>
    <button class="tablinks" onclick="openDashTab(event, 'MyProfile')">Mon profil</button>

  </div>

  <div id="MyAnswers" class="tabcontent" style="display:block;">
    <% @answers.each do |answer|%>
      <div class="row">
        <div class="col-xs-12">
          <div class="dash-answer">
            <div class="dash-answer-exercice-title">
              <h3><%= link_to answer.exercice.title, exercice_path(answer.exercice.id), class: "dash-answer-exercice-title-link" %></h3>
            <div class="dash-answer-exercice-status" id="status-replace"><p><%= answer.status %></p>
            </div>
            </div>
            <div class="dash-answer-all">
              <div class="dash-answer-exercice-begin"><p><%= answer.exercice.beginning_story %></p></div>
              <div class="dash-answer-content"><p><%= answer.content %></p></div>
              <div class="dash-answer-exercice-end"><p><%= answer.exercice.end_story %></p></div>
              <div class="date-date">
            <div class="dash-answer-exercice-date"><%= answer.exercice.updated_at.strftime("%m/%d/%y") %></div>
            </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div id="MyExercices" class="tabcontent">
    <% @exercices.each do |exercice|%>
      <div class="row">
        <div class="col-xs-12">
          <div class="dash-exercice">
            <div class="dash-answer-exercice-title"><h3><%= exercice.title %></h3>
            <div class="dash-answer-exercice-status" id="status-replace"><p><%= exercice.status %></p></div>
            </div>
            <div class="dash-exercice-all">
              <div class="dash-answer-titre-debut"><h6>Votre début :</h6></div>
              <div class="dash-answer-exercice-begin"><p><%= exercice.beginning_story %></p></div>
              <div class="dash-answer-titre-fin"><h6>Votre fin :</h6></div>
              <div class="dash-answer-exercice-end"><p><%= exercice.end_story %></p></div>
              <div class="date-date">
            <div class="dash-answer-exercice-date"><%= exercice.updated_at.strftime("%m/%d/%y") %></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div id="MyProfile" class="tabcontent">
    <div class="profile-content text-center">
      <div class="profile-avatar">
        <%= image_tag @current_user.avatar || @current_user.facebook_picture_url || 'https://api.adorable.io/avatars/285/abott@adorable.png', class: "avatar-big" %>
      </div>
      <div class='profile-stats'>
        <h5>Réponses</h5>
        <p class="numbers"><%= @current_user.answers.count %></p>
      </div>
      <div class="profile-stats">
        <h5>Exercices</h5>
        <p class="numbers"><%= @current_user.exercices.count %></p>
      </div>
      <div class="profile-stats">
        <h5>Likes</h5>
        <p class="numbers"><%= @current_user.votes.count %></p>
      </div>
    </div>
    <div class="form-container">
      <%= simple_form_for @current_user do |u| %>
        <%= u.input :username, label: "Pseudo" %>
        <%= u.input :first_name, label: "Prénom", class: 'form-control' %>
        <%= u.input :last_name, label: "Nom" %>
        <%= u.input :email, class: 'form-control'  %>
        <%= u.input :bio, class: 'form-control' %>
        <%= u.submit "Sauvegarder", class: "btn", id: "Save-btn" %>
      <% end %>
    </div>
  </div>

  <br>
  <br>
</div>

app/views/answers/like.js.erb
const likeAnswer = "<%= j render 'like', answer: @answer %>";
document.getElementById('answer_id_<%= @answer.id %>').innerHTML = likeAnswer;

app/views/answers/show.html.erb
<div class="container">
<!-- <div class="btn-prev-next">
    <div class="btn-danger hide-btn" id="answer-previous">previous</div>
    <div class="btn-danger" id="answer-next">next</div>
  </div> -->
  <div class="row">
    <div class="col-xs-12 col-sm-3">
      <div class="card card-answer-show" id="card-grid-exercices">
        <div class="card-image card-image-answer-show" style="background-image: url(<%= cl_image_path @answer.exercice.photo, crop: :fit; %>)">
        </div>
        <div class="card-answer-show-details">
          <div class="card-answer-show-titre">
            <h4><%= @answer.exercice.title %></h4>
          </div>
          <div class="card-answer-show-date">
            <p><%= @answer.exercice.updated_at %></p>
          </div>
          <div>
            <%= image_tag avatar_url = @answer.exercice.user.avatar, class: "card-answer-show-avatar" %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-9">
      <div class="answer-begin-to-end">

        <div class="answer-show-begin-story">
          <p><%= @answer.exercice.beginning_story %></p>
        </div>

        <div class="answer-show-middle-story-wrapper">

        <div class="answer-show-middle-story-all">

            <div class="answer-show-middle-story">
                <div id="ma-story" class="list-answers active">
                  <p>
                    <%= @answer.content %>
                  </p>
                </div>
                <% @answers.each do |answer| %>
                  <% if answer != @answer  %>
                    <div class="list-answers">
                      <p>
                        <%= answer.content %>
                      </p>
                    </div>
                  <% end %>
                <% end %>
            </div>

          <div class="btn-prev-next text-center">
            <ul class="list-inline">
              <li><div class="btn-danger hide-btn" id="answer-previous">previous</div></li>
              <li><div class="btn-danger" id="answer-next">next</div></li>
            </ul>
          </div>

          </div>

        </div>


        <div class="answer-show-end-story">
          <p><%= @answer.exercice.end_story %></p>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/answers/update.js.erb
<% if @answer.status == 'published' %>
  // 1. Remove le form
  document.getElementById('answer-form-block').remove();
  // 2. Append / Prepend ton answer => partial
  const new_answer = "<%= j render 'answers/show', answer: @answer %>";
  document.getElementById('answers-index').insertAdjacentHTML('afterbegin', new_answer );



$(".show-collapse").click(function() {
  $(this).hide();
  $(this).parent().find(".hide-collapse").show();
});
$( ".fa-minus" ).click(function() {
  $(".hide-collapse").hide();
  $(this).parents(".answer").find(".show-collapse").show();
});

$('.hide-comments').hide();

$(".show-comments").click(function() {
  $(this).parent().find(".answer-comments").show("fast");
  $(this).hide();
  $(this).parent().find(".hide-comments").show();
});


$( ".hide-comments" ).click(function() {
  $(this).parent().find(".answer-comments").hide("fast");
  $(this).hide();
  $(this).parent().find(".show-comments").show();
});

$('abbr').hide();

document.getElementById('text-copy').innerText = "Vous avez réalisé l'exercice";
document.getElementById('text-copy').style.opacity = 1;


<% else %>

  document.getElementById('save-auto').innerText = "...";

  setTimeout(function () {
    document.getElementById('save-auto').innerText = "Sauvegardé";
  }, 1000);

  <% end %>